/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppResultRouteImport } from './routes/_app.result'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppLeaderboardRouteImport } from './routes/_app.leaderboard'
import { Route as AppHomeRouteImport } from './routes/_app.home'
import { Route as AppExplorerRouteImport } from './routes/_app.explorer'
import { Route as AppCaptureRouteImport } from './routes/_app.capture'
import { Route as AppSpeciesNameRouteImport } from './routes/_app.species.$name'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppResultRoute = AppResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaderboardRoute = AppLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppExplorerRoute = AppExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => AppRoute,
} as any)
const AppCaptureRoute = AppCaptureRouteImport.update({
  id: '/capture',
  path: '/capture',
  getParentRoute: () => AppRoute,
} as any)
const AppSpeciesNameRoute = AppSpeciesNameRouteImport.update({
  id: '/species/$name',
  path: '/species/$name',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/capture': typeof AppCaptureRoute
  '/explorer': typeof AppExplorerRoute
  '/home': typeof AppHomeRoute
  '/leaderboard': typeof AppLeaderboardRoute
  '/profile': typeof AppProfileRoute
  '/result': typeof AppResultRoute
  '/species/$name': typeof AppSpeciesNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/capture': typeof AppCaptureRoute
  '/explorer': typeof AppExplorerRoute
  '/home': typeof AppHomeRoute
  '/leaderboard': typeof AppLeaderboardRoute
  '/profile': typeof AppProfileRoute
  '/result': typeof AppResultRoute
  '/species/$name': typeof AppSpeciesNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/capture': typeof AppCaptureRoute
  '/_app/explorer': typeof AppExplorerRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/leaderboard': typeof AppLeaderboardRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/result': typeof AppResultRoute
  '/_app/species/$name': typeof AppSpeciesNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/capture'
    | '/explorer'
    | '/home'
    | '/leaderboard'
    | '/profile'
    | '/result'
    | '/species/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/capture'
    | '/explorer'
    | '/home'
    | '/leaderboard'
    | '/profile'
    | '/result'
    | '/species/$name'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/register'
    | '/_app/capture'
    | '/_app/explorer'
    | '/_app/home'
    | '/_app/leaderboard'
    | '/_app/profile'
    | '/_app/result'
    | '/_app/species/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/result': {
      id: '/_app/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof AppResultRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leaderboard': {
      id: '/_app/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AppLeaderboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/explorer': {
      id: '/_app/explorer'
      path: '/explorer'
      fullPath: '/explorer'
      preLoaderRoute: typeof AppExplorerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/capture': {
      id: '/_app/capture'
      path: '/capture'
      fullPath: '/capture'
      preLoaderRoute: typeof AppCaptureRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/species/$name': {
      id: '/_app/species/$name'
      path: '/species/$name'
      fullPath: '/species/$name'
      preLoaderRoute: typeof AppSpeciesNameRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCaptureRoute: typeof AppCaptureRoute
  AppExplorerRoute: typeof AppExplorerRoute
  AppHomeRoute: typeof AppHomeRoute
  AppLeaderboardRoute: typeof AppLeaderboardRoute
  AppProfileRoute: typeof AppProfileRoute
  AppResultRoute: typeof AppResultRoute
  AppSpeciesNameRoute: typeof AppSpeciesNameRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCaptureRoute: AppCaptureRoute,
  AppExplorerRoute: AppExplorerRoute,
  AppHomeRoute: AppHomeRoute,
  AppLeaderboardRoute: AppLeaderboardRoute,
  AppProfileRoute: AppProfileRoute,
  AppResultRoute: AppResultRoute,
  AppSpeciesNameRoute: AppSpeciesNameRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
